### ISSUE TITLE
Searchable table view component for bikes.

### ISSUE THREAD

**Issue by klementj** [bicycle-innovation-lab/admin-app#14]
Table view of bikes with [vuetify data-tables](https://vuetifyjs.com/en/components/data-tables).

**Comment by klementj** [comment]
This component could properly be a generic table which could show, users, bikes, prjects etc. Keeping it simple for now with a specific table component to show bikes.

**Comment by Doommer43** [comment]
#19 This issue should now be resolved.

**Comment by klementj** [comment]
Thanks for keeping your eyes open @Doommer43
